Since this book tackles a rather specific use case, I assume that you have basic knowledge in Python, Django and GIT.
That said the setup you will encounter in the next chapters is kept as basic as possible, so even beginners can follow along.

This book will be based on the version stated in the list below.
However, it is possible to follow the steps with different versions – either older or newer.
The general steps will be the same.
But there might be differences in details.

On a personal note:
When I started learning programming, I often abandonded tutorials and books, because _my_ code didn’t work as the one in the book.
I want you to succeed and finish this book.
If your code does not work as epxected or you encounter a roadblock, don’t hesitate to contact me and I will try to help out.
// TODO: Add email address

=== A word about operating systems
The screenshots you will see in this book are taken on a Mac.
But you can follow this book on Windows and Linux aswell.

=== Prerequisites
* Python 3.8+
* Git
* Postgres 11+
* GitLab OR GitHub Account
* Heroku Account

==== Python and Git
Please make sure you have Python and Git installed on your system.
The easiest way is to google e.g. `install python 3 on mac` and `install git on mac` and follow the best results along.
Chances are that Python and Git are already available on your system.
While the git version is not that important, your Python version should be greater than version 3.

==== Postgres
Generally speaking you can work with any database that Django and heroku support.
(Note: https://devcenter.heroku.com/articles/sqlite3[SQLite] is not supported).
This book is based on Postgres, because you don’t need any additional elements on heroku and it is easy to setup on Django.
Since we are only setting up the database and not do fancy interactions with it, the postgres version you are using is not significant.
While it is alway a good idea to stay recent when starting new projects, you may stick to a version you already have on your system.
To see if your version works with heroku, see https://devcenter.heroku.com/articles/heroku-postgresql#version-support[this list].


==== GitLab or GitHub account
// TODO: Add actual chapter
In chapter X I will provide two variants of working with a remote repository.
You only need one account.
So you can work either with GitLab or GitHub.

==== Heroku account and Heroku CLI
Last but not least, you obviously need an heroku account to deploy your Django app on heroku.
The good thing about heroku is, that it is free (how we use it) and scalable (if needed).

Please make also sure that you have installed the Heroku Commandline Interface (CLI).


=== Checklist
*Objective:* All prerequisites are fulfilled.

==== ✔︎ Python 3+ is installed
.Terminal (any new window)
[source,shell]
----
python --version
----
-> Outputs python version 3+

[TIP]
Depending on how you installed Python 3, you have to use `python3 --version` instead.

==== ✔︎ Git is installed
.Terminal (any new window)
[source,shell]
----
git --version
----
-> Outputs any git version

==== ✔︎ Postgres is installed
.Terminal (any new window)
[source,shell]
----
postgres --version
----
-> Outputs any postgres version. Ideally 11+

==== ✔︎ GitLab or GitHub account created

==== ✔︎ Heroku account created

==== ✔︎ Heroku CLI installed
.Terminal (any new window)
[source,shell]
----
heroku --version
----
-> Outputs any heroku version