== What you need to start

To take the most of this book you need basic knowledge in Python, Django and GIT.
That said the setup you will encounter in the next chapters is kept as basic as possible, so even beginners can follow along.

This book will be based on the version stated in the list below.
It is possible to follow the steps with different versions.
The general steps will be the same, but there might be small differences.

=== Prerequisites
* Python 3.8+
* Git
* PostgreSQL 11+
* GitLab OR GitHub Account
* Heroku Account

[NOTE]
This version of the book assumes you are using
MacOS.
You can follow this book on Windows and Linux as well by adjusting the commands accordingly.

==== Python and Git
Make sure you have Python and Git installed on your system.
The easiest way is to google `install python 3 on mac` and `install git on mac`.
Chances are that Python and Git are already available on your system.
While the git version is not that important, your Python version should be version 3 or above.

==== PostgreSQL
Generally speaking you can work with any database that Django and Heroku support.
(Note: https://devcenter.heroku.com/articles/sqlite3[SQLite] is not supported).
This book is based on PostgreSQL, because you don’t need any additional elements on Heroku and it is easy to setup on Django.
Since we are only setting up the database and not do _specific_ interactions with it, the PostgreSQL version you are using is not significant.
To see if your version works with Heroku, see https://devcenter.heroku.com/articles/heroku-postgresql#version-support[this list].


==== GitLab account
To follow along you need an https://gitlab.com/users/sign_up[GitLab account].

Why GitLab and not Github?

Usually it does not matter _that much_ if you use GitLab or GitHub.
GitHub is https://devcenter.heroku.com/articles/github-integration[comfortably integrated] in heroku.
You can even create GitHub actions to create similar workflows for your heroku deployment, as we do with GitLab in this book.
I personally find working with the GitLab CI/CD pipeline more convenient.

==== Heroku account and Heroku CLI
Last but not least, you obviously need an Heroku account to deploy your Django app on Heroku.
The good thing about Heroku is, that it is free (how we use it) and scalable (if needed).

Please make also sure that you have installed the Heroku Commandline Interface (CLI).


=== Checklist

==== ✔︎ Python 3+ is installed
.Terminal (any window)
[source,shell]
----
python --version
----
-> Outputs python version 3+

[TIP]
Depending on how you installed Python 3, you have to use `python3 --version` or even `python3.8 --version` instead.

==== ✔︎ Git is installed
.Terminal (any window)
[source,shell]
----
git --version
----
-> Outputs any git version

==== ✔︎ PostgreSQL is installed
.Terminal (any window)
[source,shell]
----
postgres --version
----
-> Outputs any PostgreSQL version. Ideally 11+

==== ✔︎ GitLab or GitHub account created

==== ✔︎ Heroku account created

==== ✔︎ Heroku CLI installed
.Terminal (any window)
[source,shell]
----
heroku --version
----
-> Outputs any Heroku CLI version